metric: VOC
map_type: 11point
num_classes: 5

TrainDataset:
  name: VOCDataSet
  dataset_dir: dataset/original
  anno_path: train_list.txt
  label_list: labels.txt
  data_fields: ['image', 'gt_bbox', 'gt_class', 'difficult']

EvalDataset:
  name: VOCDataSet
  dataset_dir: dataset/original
  anno_path: val_list.txt
  label_list: labels.txt
  data_fields: ['image', 'gt_bbox', 'gt_class', 'difficult']

TestDataset:
  name: ImageFolder
  anno_path: dataset/original/labels.txt
